name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.CoverallsRepoToken }}
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Restore the dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run the tests with code coverage
        run: npm run coveralls
